### ISSUE TITLE
[feat]: Add the new design of log in and sign up page

### ISSUE THREAD

**Issue by jsdhami** [jsdhami/jenuxshop#2]
The Log In and sign Up pages are not good looking

**Describe the solution you'd like**
looking is not good, when I log in or when I create account in jenux shop.

**Describe alternatives you've considered**
add the very good design with attractive UI

**Comment by Akhilerri** [comment]
Hey I am a UI/UX Designer I can help you with this problem

**Comment by jsdhami** [comment]
> Hey I am a UI/UX Designer I can help you with this problem

Okay, You can @Akhilerri
